import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Search, Instagram, Facebook, Star, BarChart3, Target, Calendar, Download, CheckCircle2, Copy, RefreshCw, Sparkles, MapPin, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { Skeleton } from "@/components/ui/skeleton";
import { motion } from "framer-motion";
import { aiGenerateContentCalendar, aiGenerateSEOPlan, aiGenerateReviewResponse, aiAnalyzeBusiness } from "@/lib/gemini";

export default function MarketingTools() {
  const [activeTab, setActiveTab] = useState("calendar");

  // Content Calendar
  const [calBizType, setCalBizType] = useState("");
  const [calLocation, setCalLocation] = useState("");
  const [isGeneratingCal, setIsGeneratingCal] = useState(false);
  const [calResult, setCalResult] = useState<any[]>([]);

  // SEO Plan
  const [seoBizName, setSeoBizName] = useState("");
  const [seoBizType, setSeoBizType] = useState("");
  const [seoLocation, setSeoLocation] = useState("");
  const [isGeneratingSEO, setIsGeneratingSEO] = useState(false);
  const [seoResult, setSeoResult] = useState<any>(null);

  // Review Response
  const [revBizName, setRevBizName] = useState("");
  const [revBizType, setRevBizType] = useState("");
  const [revReviewText, setRevReviewText] = useState("");
  const [revStars, setRevStars] = useState("5");
  const [isGeneratingRev, setIsGeneratingRev] = useState(false);
  const [revResponse, setRevResponse] = useState("");

  // Competitor / Biz Analysis
  const [compBizName, setCompBizName] = useState("");
  const [compBizType, setCompBizType] = useState("");
  const [compLocation, setCompLocation] = useState("");
  const [isAnalyzingComp, setIsAnalyzingComp] = useState(false);
  const [compResult, setCompResult] = useState<any>(null);

  const generateCalendar = async () => {
    if (!calBizType) { toast.error("Enter a business type"); return; }
    setIsGeneratingCal(true);
    setCalResult([]);
    try {
      const posts = await aiGenerateContentCalendar(calBizType, calLocation || "your city");
      setCalResult(posts);
      toast.success(`${posts.length} posts generated by Gemini AI!`);
    } catch (err: any) {
      toast.error("Failed: " + (err.message || "Unknown"));
    } finally {
      setIsGeneratingCal(false);
    }
  };

  const generateSEO = async () => {
    if (!seoBizName || !seoBizType || !seoLocation) { toast.error("Fill all fields"); return; }
    setIsGeneratingSEO(true);
    setSeoResult(null);
    try {
      const plan = await aiGenerateSEOPlan(seoBizName, seoBizType, seoLocation);
      setSeoResult(plan);
      toast.success("Local SEO plan generated by Gemini AI!");
    } catch (err: any) {
      toast.error("Failed: " + (err.message || "Unknown"));
    } finally {
      setIsGeneratingSEO(false);
    }
  };

  const generateReviewResponse = async () => {
    if (!revBizName || !revReviewText) { toast.error("Business name and review text required"); return; }
    setIsGeneratingRev(true);
    setRevResponse("");
    try {
      const response = await aiGenerateReviewResponse(revBizName, revBizType || "local business", revReviewText, parseInt(revStars));
      setRevResponse(response);
      toast.success("AI response generated!");
    } catch (err: any) {
      toast.error("Failed: " + (err.message || "Unknown"));
    } finally {
      setIsGeneratingRev(false);
    }
  };

  const analyzeCompetitor = async () => {
    if (!compBizName || !compBizType || !compLocation) { toast.error("Fill all fields"); return; }
    setIsAnalyzingComp(true);
    setCompResult(null);
    try {
      const result = await aiAnalyzeBusiness(compBizName, compBizType, compLocation);
      setCompResult(result);
      toast.success("AI business analysis complete!");
    } catch (err: any) {
      toast.error("Failed: " + (err.message || "Unknown"));
    } finally {
      setIsAnalyzingComp(false);
    }
  };

  const copyText = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Copied!");
  };

  return (
    <div className="space-y-6 pb-12">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Marketing Toolkit</h1>
        <p className="text-muted-foreground mt-1">Gemini AI generates content calendars, SEO plans, review responses, and business analysis — all unique, every time.</p>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid grid-cols-2 md:grid-cols-4 h-auto bg-card border">
          <TabsTrigger value="calendar" className="py-2.5"><Calendar className="w-4 h-4 mr-2" /> Content Cal</TabsTrigger>
          <TabsTrigger value="seo" className="py-2.5"><Search className="w-4 h-4 mr-2" /> Local SEO</TabsTrigger>
          <TabsTrigger value="reputation" className="py-2.5"><Star className="w-4 h-4 mr-2" /> Review Reply</TabsTrigger>
          <TabsTrigger value="competitor" className="py-2.5"><Target className="w-4 h-4 mr-2" /> Biz Analysis</TabsTrigger>
        </TabsList>

        {/* CONTENT CALENDAR */}
        <TabsContent value="calendar" className="mt-6 space-y-6">
          <Card className="bg-card/50 border-border/50">
            <CardContent className="p-6 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label>Business Niche</Label>
                  <Input placeholder="e.g. Yoga Studio, Roofing Co" value={calBizType} onChange={e => setCalBizType(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Location (optional)</Label>
                  <Input placeholder="e.g. Austin, TX" value={calLocation} onChange={e => setCalLocation(e.target.value)} />
                </div>
                <div className="flex items-end">
                  <Button onClick={generateCalendar} disabled={isGeneratingCal} className="w-full gap-2">
                    {isGeneratingCal ? <><RefreshCw className="w-4 h-4 animate-spin" /> AI Generating 30 Days...</> : <><Sparkles className="w-4 h-4" /> Generate Calendar</>}
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {isGeneratingCal && <Skeleton className="h-[500px] w-full rounded-xl" />}

          {calResult.length > 0 && !isGeneratingCal && (
            <motion.div initial={{opacity:0}} animate={{opacity:1}} className="border rounded-xl bg-card overflow-hidden">
              <div className="p-4 border-b flex justify-between items-center bg-muted/30">
                <h3 className="font-semibold flex items-center gap-2"><Calendar className="w-5 h-5" /> 30-Day AI Strategy for {calBizType}</h3>
                <Button variant="outline" size="sm" onClick={() => {
                  const csv = calResult.map(p => `Day ${p.day},${p.platform},${p.type},"${p.hook}","${p.caption}"`).join("\n");
                  const blob = new Blob([`Day,Platform,Type,Hook,Caption\n${csv}`], { type: "text/csv" });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement("a"); a.href = url; a.download = "content-calendar.csv"; a.click();
                  toast.success("CSV exported!");
                }}>
                  <Download className="w-4 h-4 mr-2" /> Export CSV
                </Button>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-[1px] bg-border p-[1px] max-h-[600px] overflow-y-auto">
                {calResult.map((post: any, i: number) => (
                  <div key={i} className="bg-card p-4 min-h-[130px] flex flex-col">
                    <div className="text-xs text-muted-foreground font-medium mb-2">Day {post.day}</div>
                    <div className="flex items-center gap-1.5 mb-2">
                      {post.platform === "Instagram" ? <Instagram className="w-3.5 h-3.5 text-pink-500" /> : <Facebook className="w-3.5 h-3.5 text-blue-500" />}
                      <Badge variant="outline" className="text-[10px] h-5">{post.type}</Badge>
                    </div>
                    <p className="text-sm font-medium leading-snug mb-1">{post.hook}</p>
                    <p className="text-xs text-muted-foreground leading-relaxed line-clamp-2">{post.caption}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          )}
        </TabsContent>

        {/* LOCAL SEO */}
        <TabsContent value="seo" className="mt-6 space-y-6">
          <Card className="bg-card/50 border-border/50">
            <CardContent className="p-6 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="space-y-2">
                  <Label>Business Name</Label>
                  <Input placeholder="e.g. Joe's Plumbing" value={seoBizName} onChange={e => setSeoBizName(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Business Type</Label>
                  <Input placeholder="e.g. Plumber" value={seoBizType} onChange={e => setSeoBizType(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Location</Label>
                  <Input placeholder="e.g. Austin, TX" value={seoLocation} onChange={e => setSeoLocation(e.target.value)} />
                </div>
                <div className="flex items-end">
                  <Button onClick={generateSEO} disabled={isGeneratingSEO} className="w-full gap-2">
                    {isGeneratingSEO ? <><RefreshCw className="w-4 h-4 animate-spin" /> AI Planning...</> : <><Search className="w-4 h-4" /> Generate SEO Plan</>}
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {isGeneratingSEO && <Skeleton className="h-96 w-full rounded-xl" />}

          {seoResult && !isGeneratingSEO && (
            <motion.div initial={{opacity:0}} animate={{opacity:1}} className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Card>
                <CardHeader><CardTitle className="text-base flex items-center gap-2"><Search className="w-4 h-4 text-primary" /> Target Keywords</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                  {seoResult.keywords?.map((kw: string, i: number) => (
                    <div key={i} className="flex items-center justify-between p-2 rounded bg-muted/30 text-sm">
                      <span>{kw}</span>
                      <Button size="sm" variant="ghost" className="h-6 w-6 p-0" onClick={() => copyText(kw)}><Copy className="w-3 h-3" /></Button>
                    </div>
                  ))}
                </CardContent>
              </Card>

              <Card>
                <CardHeader><CardTitle className="text-base flex items-center gap-2"><MapPin className="w-4 h-4 text-primary" /> Service / Landing Pages</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                  {seoResult.servicePages?.map((page: string, i: number) => (
                    <div key={i} className="flex items-center justify-between p-2 rounded bg-muted/30 text-sm">
                      <span>{page}</span>
                      <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                    </div>
                  ))}
                </CardContent>
              </Card>

              <Card>
                <CardHeader><CardTitle className="text-base flex items-center gap-2"><TrendingUp className="w-4 h-4 text-primary" /> Blog Post Ideas</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                  {seoResult.blogIdeas?.map((idea: string, i: number) => (
                    <div key={i} className="flex items-center justify-between p-2 rounded bg-muted/30 text-sm">
                      <span className="mr-2">{idea}</span>
                      <Button size="sm" variant="ghost" className="h-6 w-6 p-0 shrink-0" onClick={() => copyText(idea)}><Copy className="w-3 h-3" /></Button>
                    </div>
                  ))}
                </CardContent>
              </Card>

              <Card>
                <CardHeader><CardTitle className="text-base flex items-center gap-2"><MapPin className="w-4 h-4 text-primary" /> Google Business Profile Tips</CardTitle></CardHeader>
                <CardContent className="space-y-2">
                  {seoResult.gbpTips?.map((tip: string, i: number) => (
                    <div key={i} className="flex items-start gap-2 p-2 rounded bg-muted/30 text-sm">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                      <span>{tip}</span>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </motion.div>
          )}
        </TabsContent>

        {/* REVIEW RESPONSE */}
        <TabsContent value="reputation" className="mt-6 space-y-6">
          <Card className="bg-card/50 border-border/50">
            <CardContent className="p-6 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label>Business Name</Label>
                  <Input placeholder="e.g. Mario's Pizza" value={revBizName} onChange={e => setRevBizName(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Business Type</Label>
                  <Input placeholder="e.g. Restaurant" value={revBizType} onChange={e => setRevBizType(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Star Rating</Label>
                  <Select value={revStars} onValueChange={setRevStars}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {["1","2","3","4","5"].map(s => <SelectItem key={s} value={s}>{s} ⭐</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-2">
                <Label>Actual Review Text</Label>
                <Textarea
                  placeholder="Paste the actual customer review here..."
                  value={revReviewText}
                  onChange={e => setRevReviewText(e.target.value)}
                  className="min-h-[80px]"
                />
              </div>
              <Button onClick={generateReviewResponse} disabled={isGeneratingRev} className="w-full gap-2">
                {isGeneratingRev ? <><RefreshCw className="w-4 h-4 animate-spin" /> AI Writing Response...</> : <><Sparkles className="w-4 h-4" /> Generate AI Response</>}
              </Button>
            </CardContent>
          </Card>

          {revResponse && !isGeneratingRev && (
            <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}>
              <Card className="border-primary/30 bg-primary/5">
                <CardHeader>
                  <CardTitle className="text-base flex items-center justify-between">
                    <span className="flex items-center gap-2"><Star className="w-4 h-4 text-primary" /> AI-Generated Response</span>
                    <Button size="sm" variant="outline" onClick={() => copyText(revResponse)}><Copy className="w-3 h-3 mr-1" /> Copy</Button>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <Textarea
                    value={revResponse}
                    onChange={e => setRevResponse(e.target.value)}
                    className="min-h-[100px] border-none bg-transparent focus-visible:ring-0 shadow-none resize-none"
                  />
                  <p className="text-xs text-muted-foreground mt-2">Edit as needed before posting to Google.</p>
                </CardContent>
              </Card>
            </motion.div>
          )}
        </TabsContent>

        {/* BUSINESS ANALYSIS */}
        <TabsContent value="competitor" className="mt-6 space-y-6">
          <Card className="bg-card/50 border-border/50">
            <CardContent className="p-6 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="space-y-2">
                  <Label>Business Name</Label>
                  <Input placeholder="e.g. Joe's Roofing" value={compBizName} onChange={e => setCompBizName(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Business Type</Label>
                  <Input placeholder="e.g. Roofing Company" value={compBizType} onChange={e => setCompBizType(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Location</Label>
                  <Input placeholder="e.g. Dallas, TX" value={compLocation} onChange={e => setCompLocation(e.target.value)} />
                </div>
                <div className="flex items-end">
                  <Button onClick={analyzeCompetitor} disabled={isAnalyzingComp} className="w-full gap-2">
                    {isAnalyzingComp ? <><RefreshCw className="w-4 h-4 animate-spin" /> AI Analyzing...</> : <><BarChart3 className="w-4 h-4" /> Analyze Business</>}
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {isAnalyzingComp && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {[1,2,3,4].map(i => <Skeleton key={i} className="h-40 rounded-xl" />)}
            </div>
          )}

          {compResult && !isAnalyzingComp && (
            <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-6">
              <div className="flex items-center justify-between p-4 rounded-xl bg-card border">
                <div>
                  <h3 className="font-bold text-lg">{compBizName}</h3>
                  <p className="text-sm text-muted-foreground">{compBizType} · {compLocation}</p>
                </div>
                <div className="text-right">
                  <div className="text-3xl font-bold text-primary">{compResult.score}</div>
                  <div className="text-xs text-muted-foreground">Lead Score / 100</div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card>
                  <CardHeader><CardTitle className="text-base text-destructive">Problems Found</CardTitle></CardHeader>
                  <CardContent className="space-y-2">
                    {compResult.problems?.map((p: string, i: number) => (
                      <div key={i} className="flex items-start gap-2 text-sm">
                        <span className="text-destructive font-bold shrink-0">•</span>{p}
                      </div>
                    ))}
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader><CardTitle className="text-base text-primary">Pitch Angles</CardTitle></CardHeader>
                  <CardContent className="space-y-3 text-sm text-muted-foreground">
                    {compResult.websiteOpportunity && <p><span className="font-medium text-foreground">Website:</span> {compResult.websiteOpportunity}</p>}
                    {compResult.seoOpportunity && <p><span className="font-medium text-foreground">SEO:</span> {compResult.seoOpportunity}</p>}
                    {compResult.orderingOpportunity && <p><span className="font-medium text-foreground">Conversion:</span> {compResult.orderingOpportunity}</p>}
                  </CardContent>
                </Card>
              </div>

              {compResult.revenueOpportunity && (
                <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 text-sm">
                  <span className="font-semibold">💰 Revenue Opportunity: </span>{compResult.revenueOpportunity}
                </div>
              )}

              <div className="p-4 rounded-xl bg-card border">
                <h4 className="font-medium mb-2">AI Summary</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">{compResult.summary}</p>
              </div>
            </motion.div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
